"""Shared constants for VK PDF catalog extraction."""
from __future__ import annotations

BRAND = "VK Tiles & Granites"

FEATURES = [
    "Low Water Absorption",
    "High Breaking Strength",
    "Frost Resistant",
    "Stain Resistant",
    "Easy Maintenance",
    "ISO 9001:2015 Certified",
]

APPLICATIONS = {
    "gvt-pgvt": ["Living Room", "Bedroom", "Commercial Spaces", "Hotels", "Office"],
    "wooden-strip": ["Living Room", "Bedroom", "Commercial Spaces"],
    "wall-tiles": ["Bathroom", "Kitchen", "Living Room", "Bedroom", "Accent Walls"],
    "elevation-tiles": ["Building Facade", "Exterior Walls", "Commercial Elevation"],
    "parking-tiles": ["Parking Areas", "Driveways", "Commercial Outdoor"],
}

PACKING_DEFAULTS = {
    "300x450 MM": {"thickness": "7.5 MM", "tilesPerBox": 6, "coverage": "0.81 SQM", "weight": "16 KG"},
    "300x600 MM": {"thickness": "9 MM", "tilesPerBox": 5, "coverage": "0.90 SQM", "weight": "18 KG"},
    "400x400 MM": {"thickness": "8 MM", "tilesPerBox": 5, "coverage": "0.80 SQM", "weight": "18 KG"},
    "600x600 MM": {"thickness": "9 MM", "tilesPerBox": 4, "coverage": "1.44 SQM", "weight": "28 KG"},
    "600x1200 MM": {"thickness": "9 MM", "tilesPerBox": 2, "coverage": "1.44 SQM", "weight": "30 KG"},
    "800x1600 MM": {"thickness": "9 MM", "tilesPerBox": 2, "coverage": "2.56 SQM", "weight": "42 KG"},
}

MATERIAL = {
    "gvt-pgvt": "Glazed Vitrified Tile (GVT/PGVT)",
    "wooden-strip": "Porcelain Wood-Look Tile",
    "wall-tiles": "Ceramic Wall Tile",
    "elevation-tiles": "Elevation / High Depth Tile",
    "parking-tiles": "Parking Floor Tile",
}

# Indexed PDF configs for legacy interactive catalogs (optional).
LEGACY_PDF_CONFIGS: dict[str, dict] = {
    "MATT.pdf": {
        "series_slug": "matt",
        "collection": "Matt Collection",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Random",
    },
    "WOODEN MATT.pdf": {
        "series_slug": "wooden-matt",
        "collection": "Wood Collection",
        "category": "wooden-strip",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Matt Wood",
        "pattern": "Wood",
    },
    "GLOSSY ENDLESS 1.pdf": {
        "series_slug": "glossy-endless-1",
        "collection": "Glossy Endless",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Endless",
    },
    "GLOSSY ENDLESS 2.pdf": {
        "series_slug": "glossy-endless-2",
        "collection": "Glossy Endless 2",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Endless",
    },
    "GLOSSY RANDOM 1.pdf": {
        "series_slug": "glossy-random-1",
        "collection": "Glossy Random",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Random",
    },
    "GLOSSY RANDOM 2.pdf": {
        "series_slug": "glossy-random-2",
        "collection": "Glossy Random 2",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Random",
    },
    "GLOSSY STAUARIO & ONYX.pdf": {
        "series_slug": "glossy-statuario-onyx",
        "collection": "Glossy Statuario & Onyx",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Marble",
    },
    "HIGH GLOSSY.pdf": {
        "series_slug": "high-glossy",
        "collection": "High Glossy",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Random",
    },
    "NEW GLOSSY 2.pdf": {
        "series_slug": "new-glossy-2",
        "collection": "New Glossy 2",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Random",
    },
    "SUPER HIGH GLOSSY.pdf": {
        "series_slug": "super-high-glossy",
        "collection": "Super High Glossy",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Random",
    },
    "INKY_1.pdf": {
        "series_slug": "inky-1",
        "collection": "Inky Collection",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Inky",
    },
    "INKY_2.pdf": {
        "series_slug": "inky-2",
        "collection": "Inky Collection 2",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Inky",
    },
    "CARVING.pdf": {
        "series_slug": "carving",
        "collection": "Matt Carving",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Carving",
        "pattern": "Carving",
    },
    "VALENZA NEW CARVING.pdf": {
        "series_slug": "valenza-new-carving",
        "collection": "Carving Collection",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Carving",
        "pattern": "Carving",
        "mode": "sequential",
        "start_page": 5,
    },
    # VKProducts — carving series
    "C-1.pdf": {
        "series_slug": "c-1",
        "collection": "Carving C-1",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Carving",
        "pattern": "Carving",
    },
    "C-2.pdf": {
        "series_slug": "c-2",
        "collection": "Carving C-2",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Carving",
        "pattern": "Carving",
    },
    "C-3.pdf": {
        "series_slug": "c-3",
        "collection": "Carving C-3",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Carving",
        "pattern": "Carving",
    },
    "C-4.pdf": {
        "series_slug": "c-4",
        "collection": "Carving C-4",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Carving",
        "pattern": "Carving",
    },
    "C-6.pdf": {
        "series_slug": "c-6",
        "collection": "Carving C-6",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Carving",
        "pattern": "Carving",
    },
    "GOLDEN SERIES C-5.pdf": {
        "series_slug": "golden-series-c-5",
        "collection": "Golden Series C-5",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Golden",
    },
    "3D.pdf": {
        "series_slug": "3d",
        "collection": "3D Collection",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "3D",
    },
    # Elevation series
    "ELE-1.pdf": {
        "series_slug": "ele-1",
        "collection": "Elevation ELE-1",
        "category": "elevation-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "High Depth",
        "pattern": "Elevation",
    },
    "ELE-2.pdf": {
        "series_slug": "ele-2",
        "collection": "Elevation ELE-2",
        "category": "elevation-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "High Depth",
        "pattern": "Elevation",
    },
    "ELE-3.pdf": {
        "series_slug": "ele-3",
        "collection": "Elevation ELE-3",
        "category": "elevation-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "High Depth",
        "pattern": "Elevation",
    },
    "ELE-4.pdf": {
        "series_slug": "ele-4",
        "collection": "Elevation ELE-4",
        "category": "elevation-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "High Depth",
        "pattern": "Elevation",
    },
    "ELE-5.pdf": {
        "series_slug": "ele-5",
        "collection": "Elevation ELE-5",
        "category": "elevation-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "High Depth",
        "pattern": "Elevation",
    },
    # Themed wall collections
    "FISH.pdf": {
        "series_slug": "fish",
        "collection": "Fish Collection",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Fish",
    },
    "FLOWER.pdf": {
        "series_slug": "flower",
        "collection": "Flower Collection",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Flower",
    },
    "NEW FLOWER.pdf": {
        "series_slug": "new-flower",
        "collection": "New Flower",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Flower",
    },
    "SCENERY.pdf": {
        "series_slug": "scenery",
        "collection": "Scenery Collection",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Scenery",
    },
    "POOJA.pdf": {
        "series_slug": "pooja",
        "collection": "Pooja Collection",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Pooja",
    },
    "POOJA ROOM.pdf": {
        "series_slug": "pooja-room",
        "collection": "Pooja Room",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Pooja",
    },
    "KITCHEN-1.pdf": {
        "series_slug": "kitchen-1",
        "collection": "Kitchen 1",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Kitchen",
    },
    "KITCHEN-2.pdf": {
        "series_slug": "kitchen-2",
        "collection": "Kitchen 2",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Kitchen",
    },
    "W&M-1.pdf": {
        "series_slug": "w-m-1",
        "collection": "Wall & Matt 1",
        "category": "wall-tiles",
        "size": "300x600 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Wall & Matt",
    },
    "W&M-2.pdf": {
        "series_slug": "w-m-2",
        "collection": "Wall & Matt 2",
        "category": "wall-tiles",
        "size": "300x600 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Wall & Matt",
    },
    "SPECIAL COLOUR.pdf": {
        "series_slug": "special-colour",
        "collection": "Special Colour",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Glossy",
        "surface": "Polished",
        "pattern": "Special",
    },
    "EXTERIA COLLECTION.pdf": {
        "series_slug": "exteria-collection",
        "collection": "Exteria Collection",
        "category": "elevation-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "High Depth",
        "pattern": "Exterior",
    },
    "INTERIOR COLLECTION.pdf": {
        "series_slug": "interior-collection",
        "collection": "Interior Collection",
        "category": "wall-tiles",
        "size": "300x600 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Interior",
    },
    "KITCHEN COLLECTION.pdf": {
        "series_slug": "kitchen-collection",
        "collection": "Kitchen Collection",
        "category": "wall-tiles",
        "size": "300x450 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Kitchen",
    },
    "MATT-1.pdf": {
        "series_slug": "matt-1",
        "collection": "Matt Collection 1",
        "category": "gvt-pgvt",
        "size": "600x1200 MM",
        "finish": "Matt",
        "surface": "Matt",
        "pattern": "Random",
    },
}

INDEX_MIN_LINKS = 6
MIN_TILE_DIM = 280
MIN_TILE_AREA = 90000
MIN_HERO_AREA = 180000
MAX_ASPECT_RATIO = 1.45
MAX_FULLPAGE_ASPECT_RATIO = 2.6

SKIP_NAME_TOKENS = frozenset({
    "OUTLOOK", "COLLECTION", "FINISH", "RANDOM", "MATT", "GLOSSY", "HOUSE",
    "OUTDOOR", "TILES", "OF", "FLOOR", "GRES", "PUNCH", "SERIES", "BEST",
    "SELLING", "PRODUCT", "INSIDE", "VALENZA", "VK", "DIGITAL", "PLAIN",
    "SAND", "CARVING", "ENDLESS", "THE", "WOOD", "INKY", "HIGH", "SUPER",
    "NEW", "WL", "GLITTER",
})

CATEGORY_LABELS = {
    "gvt-pgvt": "GVT / PGVT Floor Tiles",
    "wooden-strip": "Wooden Strip",
    "wall-tiles": "Wall Tiles",
    "elevation-tiles": "Elevation Tiles",
    "parking-tiles": "Parking Tiles",
}
